### ISSUE TITLE
Introduce a build-step

### ISSUE THREAD

**Issue by addyosmani** [nasa/code-nasa-gov#1]
There's some low-hanging fruit (such as concat/minification) we could tackle by adding a build step. To start, I was thinking of doing something very simple with npm scripts/adding a package.json. We could evolve this once we come up with a larger refresh.

```html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular-resource.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular-route.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
```

**Comment by samccone** [comment]
👍 all the templates are hitting the network also, we should prob build these into a bundle as well.

**Comment by Saturate** [comment]
How about a gulp script? It could be expanded to allow the css to be sass/scss, with autoprefixer and minify.

I'm willing to do a PR on this, and shouldn't take long to implement.

**Comment by addyosmani** [comment]
I'm personally in favor of (for now) trying to keep this super simple (why I suggested npm scripts). If we end up needing to include more than a few lines for the build pipeline, I'd say sure on switching to Gulp. Let's see where it goes :)
