### ISSUE TITLE
Move all $http invocations into new services module

### ISSUE THREAD

**Issue by ZachMoreno** [nasa/code-nasa-gov#11]
`/js/controller.js` [invokes the `$http` provider](https://github.com/nasa/code-nasa-gov/blob/master/js/controllers.js#L11) twice to fetch JSON files located in `/data`. I'm proposing that we create a new services module that will expose 2 services through the use of `$resource`, one that returns`/data/SRA.json` & another that returns `/data/catalog.json`. The services module will then be injected as a dependency of the controllers. This is in an effort to separate concerns & uphold the recommended [best practice](http://stackoverflow.com/questions/29663859/fetch-data-from-angularjs-controller).

Please assign me to this issue & I'll send along a pull request.

**Comment by ZachMoreno** [comment]
Submitted #12

**Comment by JustinGOSSES** [comment]
no longer applicable
