### ISSUE TITLE
Controllers are not a defined Angular module

### ISSUE THREAD

**Issue by ZachMoreno** [nasa/code-nasa-gov#14]
`/js/controller.js` does not define an angular module, but instead defines vanilla Ctrl functions. While this approach works, it would provide maximum code reuse & modularity to define an Angular module for all controllers that is then a dependency of the root app.

Please assign me to this issue & I'll happily send along a pull request.

**Comment by addyosmani** [comment]
Please feel free to go for it, @ZachMoreno. Looking at https://github.com/nasa/openmct/pull/1162 it appears you've already signed the CLA so we should be all good on that front.

**Comment by JustinGOSSES** [comment]
no longer applicable
