### ISSUE TITLE
Decrease cost of fetching/parsing partials

### ISSUE THREAD

**Issue by addyosmani** [nasa/code-nasa-gov#17]
Fetching partials currently costs us almost 2000ms:
![](https://i.imgur.com/5u6HiMU.jpg)

and a whole lot of time in `$apply` and `$digest`. Given this isn't particularly complex, we're doing a little too much work here (across tags, social buttons, licenses)

![](https://i.imgur.com/8jgRz2x.jpg)

**Comment by samccone** [comment]
partial fetching will be fixed by:
https://github.com/nasa/code-nasa-gov/issues/1#issuecomment-244582146

but this is dependent on how things are deployed.

If we can just deploy the site to gh-pages this all gets a lot easier :)

**Comment by addyosmani** [comment]
Fixed in https://github.com/nasa/code-nasa-gov/issues/18. Next up is a lil work on the list.
