### ISSUE TITLE
[nasa-next] Guide -> SRAs section should look the same as the design mock

### ISSUE THREAD

**Issue by frankiefu** [nasa/code-nasa-gov#25]
Currently (https://polymer-nasa.appspot.com):

<img width="379" alt="screen shot 2016-11-04 at 4 37 57 pm" src="https://cloud.githubusercontent.com/assets/116360/20025615/4057ca1a-a2ad-11e6-940a-bd6cf8c49ea2.png"><br>

Design mock:

<img width="461" alt="screen shot 2016-11-04 at 4 40 04 pm" src="https://cloud.githubusercontent.com/assets/116360/20025622/5febdbaa-a2ad-11e6-83e4-3737fc0a11cb.png">

**Comment by JustinGOSSES** [comment]
no longer applicable
