### ISSUE TITLE
[nasa-next] Missing the share icon in the project

### ISSUE THREAD

**Issue by frankiefu** [nasa/code-nasa-gov#26]
Project is missing the share icon on the right.

From the design mock:

![screen shot 2016-11-04 at 5 06 54 pm](https://cloud.githubusercontent.com/assets/116360/20025937/3814f414-a2b1-11e6-9765-76170a631492.png)
![screen shot 2016-11-04 at 5 07 14 pm](https://cloud.githubusercontent.com/assets/116360/20025938/3a06fd30-a2b1-11e6-89a2-88873da4d5bc.png)

**Comment by santokii** [comment]
Maybe we can reuse what's currently on https://design.google.com/articles/design-is-never-done/ (scroll to bottom right)?
