### ISSUE TITLE
[nasa-next] Mobile homepage should have the background image centered

### ISSUE THREAD

**Issue by frankiefu** [nasa/code-nasa-gov#27]
Currently (https://polymer-nasa.appspot.com):

<img width="413" alt="screen shot 2016-11-04 at 5 24 38 pm" src="https://cloud.githubusercontent.com/assets/116360/20026135/a2c76aba-a2b3-11e6-8a0f-0aa8da0e46ac.png"><br>

We should try to make it to look like this (from design mock):

![screen shot 2016-11-04 at 5 25 46 pm](https://cloud.githubusercontent.com/assets/116360/20026141/bc4c3394-a2b3-11e6-8796-2a0913ab55c2.png)

I think there is a project background asset for mobile.  We should switch to that when it's in mobile layout. Also make the header height be '100vh'.

**Comment by JustinGOSSES** [comment]
done
