### ISSUE TITLE
[nasa-next] Avoid FOUC

### ISSUE THREAD

**Issue by frankiefu** [nasa/code-nasa-gov#29]
We should try to minimize FOUC as much as possible.  Currently when you reload https://polymer-nasa.appspot.com you will see the footer shows up at the top right below the tabs and then immediately disappears after the list is rendered.  To avoid FOUC one way we could do is to make `<code-nasa-app>` has `min-height: 100vh` so the footer is always at the bottom.

**Comment by keanulee** [comment]
There's no guarantee that the content is at least 100vh (e.g. the share page is really short)
