### ISSUE TITLE
Desktop homepage should default to having the search field selected

### ISSUE THREAD

**Issue by santokii** [nasa/code-nasa-gov#32]
Since this is the primary action on this page, let's have the cursor selected on the search field by default on load just for desktop.

**Comment by keanulee** [comment]
I can set `autofocus` on the input, but this will also focus it on mobile (it'll shot a blinking cursor but not open the keyboard).

**Comment by santokii** [comment]
@frankiefu Is there a way to do this so it'd only autofocused on desktop?
