### ISSUE TITLE
Bar appears behind on desktop nav on scroll

### ISSUE THREAD

**Issue by santokii** [nasa/code-nasa-gov#33]
![screen shot 2016-11-07 at 11 18 35 am](https://cloud.githubusercontent.com/assets/11649557/20072140/1ecb02c8-a4dc-11e6-90c3-a247eb3b2c0b.png)

Please remove for desktop

**Comment by keanulee** [comment]
This is intentional since the header may be over list content

**Comment by santokii** [comment]
The header isn't ever overlapping content because its not anchored when you scroll down so please remove.

**Comment by JustinGOSSES** [comment]
no longer applicable
