### ISSUE TITLE
Can we remove the orange selected state?

### ISSUE THREAD

**Issue by santokii** [nasa/code-nasa-gov#44]
When you tap on the search bar the default orange selected state shows up. Is it possible to remove this? Thanks!

![image](https://cloud.githubusercontent.com/assets/11649557/20157258/e5d1a8f6-a688-11e6-9303-2748fc547a68.png)

**Comment by frankiefu** [comment]
We need to have a replacement for the focus state, e.g. different underbar color when the input is in focus.

**Comment by santokii** [comment]
#757575 (and a few pixels bigger would be much better than orange if possible!!

**Comment by keanulee** [comment]
Note that this is the default focused styling provided by Chrome on Android, and different browsers provide different default focused styling (e.g. Chrome and Safari on Mac use a blue outline, and Safari on iOS doesn't have any styling). If we set a custom focused styling, it will apply on all browsers.

RE the suggestion, I don't think the contrast with that would be enough (`outline: 4px solid #757575`):
![image](https://cloud.githubusercontent.com/assets/1319720/20225142/a30bb7ae-a7f6-11e6-9166-b1bd19f6a1b5.png)

**Comment by santokii** [comment]
Yeah, that's not ideal but better than the orange. Let's go with the
default for now and hope that it changes soon!

**Comment by JustinGOSSES** [comment]
now blue
