### ISSUE TITLE
Strange dark blue line under Guide page header image (desktop and mobile)

### ISSUE THREAD

**Issue by santokii** [nasa/code-nasa-gov#45]
Not sure where this is coming from (could be my bad for providing multiple background colors) but there seems to be a blue band appearing below the header image? If this is from the png, let me know and I'll provide a new one!

![image](https://cloud.githubusercontent.com/assets/11649557/20157873/3ddda6aa-a68c-11e6-8be3-d761167b45e3.png)

**Comment by JustinGOSSES** [comment]
appears to be gone
