### ISSUE TITLE
Slow first load

### ISSUE THREAD

**Issue by denar90** [nasa/code-nasa-gov#49]
I was trying to load it using my phone (Mi Redmi 3) and got this results. 
Either very very first load or after clearing all browser data it takes > 10 seconds.

![code nasa gov first](https://cloud.githubusercontent.com/assets/6231516/20246066/9791386e-a9b7-11e6-99ac-83650e4972e1.png)

Hot stuff is `code-nasa-app.html`.

With second load everything is fine (files are precached).

![code nasa gov second](https://cloud.githubusercontent.com/assets/6231516/20246088/fdb02e3e-a9b7-11e6-80b1-b54858217c23.png)

We can use here either vulcanize/crisper. @addyosmani any thoughts?

**Update**:

Moreover, here pwmetrics results

![nasa code gov pwmetrics](https://cloud.githubusercontent.com/assets/6231516/20248669/8df79e30-a9f1-11e6-8f6d-5e4ba1193b60.png)

**Comment by addyosmani** [comment]
@denar90 Thanks for the bug report. Could you share what network conditions you were testing over? I profiled the app before launch on slow 3G and we saw pretty good metrics across the board, but happy to take another look.

**Comment by samccone** [comment]
@denar90 mind sharing a timeline here
https://chromedevtools.github.io/timeline-viewer/

---

It looks like the network is the real cost here for you not really the JS overhead.

**Comment by denar90** [comment]
@addyosmani @samccone thanks for reply. 

<hr/>
My network conditions on PC (MacBook Pro 2011, 2.4 GHz Intel Core i5, 4 GB RAM) is ~15Mbps. Profiled with no network throttling, no CPU throttling.
Here is profiling.

**First load**, after `Dev tools -> Application -> Clear storage -> Clear site data`.

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/ce101b5e4b6633fdb11947a9fd387924/raw/068719f257608d594d645da64f68c546b38df818/code.nasa.gov.first-load

**Second load** (without clearing caches).

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/18c2221d6616655812815047f4022aad/raw/de5c7cd91805ee20c692f2f8b0d51d61288b43fb/code.nasa.gov.second-load


<hr/>
Mobile (Xiaomi Redmi 3, 1,5 GHz CPU, 2 GB RAM) network conditions ~2 Mbps.

**First load**, after `Dev tools -> Application -> Clear storage -> Clear site data`

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/b63ac7f98dace857d612a9cfa99b56ee/raw/a7f0556ee71489f34988fb845a8d15e97af5590f/mobile.code.nasa.gov.first-load

**Second load** (without clearing caches).

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/b0c243f62cc0c6fb022f72037733ee0e/raw/857f5548686e1fb3fa499365eb11921c914144f6/mobile.code.nasa.gov.second-load

And `pwmetrics` results one more time.

![code nasa gov pwmetrics](https://cloud.githubusercontent.com/assets/6231516/20368142/6d232f82-ac5b-11e6-905f-68b20f9c5cd4.png)

~15Mbps have not to be a problem, have to? 
Maybe here present some place for opportunity 😉  ?

**Comment by denar90** [comment]
I was really interested if it's network influence, so I found good network connection and made profiling on it.

Connection on PC ~85 Mbps.

First load, on PC (cleaned cache)

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/e4d351fb670dbca7c73d3bf8a1dcee2e/raw/23ee0c94d01f876c40c91708facd8f9aaf407d25/code.nasa.gov.first.fast-connection

Second load (without cleaning cache).

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/7476786bb57b43421bdffa0c469618ef/raw/a7b416b65f9d0ac83105c76817bc817f1e281931/code.nasa.gov.second.fast-connection


Connection on Mobile ~11 Mbps

First load, on PC (cleaned cache)

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/119761ecec603317967a6bee9f953f64/raw/70eae0d8ac85c3c444495512f5c607858293f9a3/mobile.code.nasa.gov.first.fast-connection

Second load (without cleaning cache).

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/23aff6db1229be6d2ae24f3807b139d9/raw/47b5d3ae8e8866f9f57b721f4e389b58165603dc/mobile.code.nasa.gov.second.fast-connection


Here compare table for Mobile on different speed when first paint (paint recognized by user) is appear 

| Mbps ~ | First load (ms) | Second Load (ms) |
|--------|:---------------:|:----------------:|
|    2   |       4700      |        920       |
|   11   |       3800      |        990       |

And for PC

| Mbps ~ | First load (ms) | Second Load (ms) |
|--------|:---------------:|:----------------:|
|   15   |       4200      |        650       |
|   85   |       3300      |        660       |

**Comment by samccone** [comment]
hmm looking at the trace, I get a feeling that the pipe size or bandwidth is not the real issue here rather the round trip cost to the server and back.

@denar90 mind running a traceroute on the site for me? I think that perhaps that gh pages have no close   edge cache server location to you and so your request and the response is taking a long journey to get to you.

**Comment by denar90** [comment]
Traceroute - https://gist.github.com/denar90/0cd2771ec643dc3b772810d289a82200
Moreover, I cloned repo, run bundled version (regular 3G and 2x CPU throttling) with cleaned cache.
https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/denar90/e87619849321a960a694d803fd49549b/raw/61f34174eb777a067bb6e257d4ef3717d096df26/code.nasa.gov.local.first.regular-3G

**Comment by denar90** [comment]
@samccone should we close this one.

**Comment by denar90** [comment]
Yeap, it was round trip problem. Thank you guys for your responses 👍
