### ISSUE TITLE
Show search summary without scrolling down

### ISSUE THREAD

**Issue by usergenic** [nasa/code-nasa-gov#51]
My experience is I have to scroll down to see if there were search hits.  I think I should see some level search result summary without scrolling down.

Current experience...
<img width="657" alt="screen shot 2016-11-14 at 4 19 13 pm" src="https://cloud.githubusercontent.com/assets/578/20288158/2dea3d96-aa86-11e6-9841-b6e8f1dd5876.png">

Desired summary (shows after I scroll down)...
<img width="779" alt="screen shot 2016-11-14 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/578/20288167/3ed437f6-aa86-11e6-80b1-64204ad6a4f2.png">

**Comment by akhenry** [comment]
+1 this. I also experience this on a 13" retina MBP. After entering search terms and hitting enter there is no visual feedback at all that search results have been returned.

**Comment by amitsin6h** [comment]
can I work on this

**Comment by JustinGOSSES** [comment]
yes

**Comment by JustinGOSSES** [comment]
To be clear, it would be nice if when you opened the page, the results lists of projects was visible.

**Comment by JustinGOSSES** [comment]
We have merged a pull request that adds a small arrow that indicates there is context below, but we could probably make it more obvious.
