### ISSUE TITLE
blank screen on Firefox Developer Edition 51.0a2

### ISSUE THREAD

**Issue by marzepani** [nasa/code-nasa-gov#52]
The page does not load on the current Firefox Dev Edition 51.0a2 (2016-11-14).

![screen shot 2016-11-17 at 10 52 40](https://cloud.githubusercontent.com/assets/3640237/20384438/2371095a-acb4-11e6-974f-41611036487b.png)

**Comment by addyosmani** [comment]
cc @keanulee Fwiw, I just tested in the latest Firefox Nightly and everything is working as expected there.

**Comment by marzepani** [comment]
Thank you @addyosmani, I retested the site with other releases.

OK:
- Firefox 50.0
- Firefox Nightly 53.0a1 (2016-11-16) (64-bit) and 53.0a1 (2016-11-26) (64-bit)

NOT OK:
- Firefox Aurora 51.0a2 (2016-11-14) (64-bit) and 52.0a2 (2016-11-26) (64-bit)
- Firefox Developer Edition 52.0a2 (2016-11-25) (64-bit) and 52.0a2 (2016-11-26) (64-bit)

I have no clue if this helps, but I thought it might be worth the time. :-)
