### ISSUE TITLE
The url "http://nams.nasa.gov/nams/asset/227756" not working.

### ISSUE THREAD

**Issue by Ajeey** [nasa/code-nasa-gov#57]
This site can’t be reached
nams.nasa.gov’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by jasonduley** [comment]
this is an internal NASA site.  We'll look into making this clearer on the actually site instructions.  Thanks for pointing this out!

**Comment by cgentemann** [comment]
link still doesn't work.  Is there a way for outside-nasa people to apply?  other instructions?  thanks!

**Comment by JustinGOSSES** [comment]
No, this is for releasing NASA developed code. <-@cgentemann
