### ISSUE TITLE
SRA link in Guide doesn't work

### ISSUE THREAD

**Issue by larkin** [nasa/code-nasa-gov#58]
The link to the SRA list in the first step of the [guide](https://code.nasa.gov/#/guide) doesn't go anywhere.  What is the intent of this?  is it:

a) link to SRA list lower on the page
b) link to separate page for submitting requests to SRA
c) something else

**Comment by keanulee** [comment]
#57

**Comment by JustinGOSSES** [comment]
fixed in latest change will be reflected when deployed
