### ISSUE TITLE
need menu bar text to have background color when scrolling up after down

### ISSUE THREAD

**Issue by JustinGOSSES** [nasa/code-nasa-gov#60]
Need menu bar text [Project Guide Share] to have background color when scrolling up after down. 

Currently, there is only text and no background, so things get hard to read when menubar text overlays normal text. 

To see this you have to scroll down on projects page on desktop and then scroll up.

<img width="989" alt="Screen Shot 2019-04-04 at 11 36 22 AM" src="https://user-images.githubusercontent.com/11600445/55572807-13fb5180-56ce-11e9-9a7c-3634c3685b64.png">

**Comment by andynoelker** [comment]
What do you think about a gradient that spans the width of the page? Something like this:

![banner](https://user-images.githubusercontent.com/4426398/56245623-80c70200-6065-11e9-9615-68454099e9bc.jpg)

![banner](https://user-images.githubusercontent.com/4426398/56246003-6fcac080-6066-11e9-90e2-8b69fc6cbd40.gif)

This is using `#212121` as the gradient color.

**Comment by JustinGOSSES** [comment]
Works for me. Can you submit a pull request with just that change @andynoelker
