### ISSUE TITLE
Addition of Meta Keywords tag in index.html

### ISSUE THREAD

**Issue by shivaylamba** [nasa/code-nasa-gov#66]
We can add keywords such as NASA Open Source, NASA for better Search Engine Optimization based off my PR #65

**Comment by JustinGOSSES** [comment]
Can you be more specific what you're suggesting or questioning?

**Comment by shivaylamba** [comment]
@JustinGOSSES In reference to my PR : https://github.com/nasa/code-nasa-gov/pull/65 . What I Intended is that using meta keywords tag helps in increasing the SEO for the website when searches relevant to the keywords mentioned are done on search engines. So I just wanted to have these included so that the relevance and searchability of the website increases.

**Comment by JustinGOSSES** [comment]
Merged via #65
