### ISSUE TITLE
Consider using webpack, parcel or gulp for building

### ISSUE THREAD

**Issue by evenstensberg** [nasa/code-nasa-gov#70]
I think Bower is outdated, using webpack, parcel or gulp is probably better to avoid security risks, outdated dependencies or falling behind on versioning.

**Comment by jMuzsik** [comment]
The first step here would be to migrate from bower to npm. This has the added benefit of being able to upgrade the dependencies as current versions of polymer do not work with bower. 

As in, this app uses Polymer version 1.6 while the current version is, 3.3.0. So, there is a lot of useful code to be integrated for (likely) minimal work.

**Comment by JustinGOSSES** [comment]
If someone wants to try to update this to newer version of Polymer, we'd definitely appreciate it. It is on the todo list of the maintainers but low in priority relative to other things elsewhere.

**Comment by justinfagnani** [comment]
I just ran the site through modulizer and I have a somewhat working projects page showing up. Search isn't working yet. I can upload what I have into a fork in a bit.
