### ISSUE TITLE
last pull request broke scrolling on first page, only 12 results show up initially

### ISSUE THREAD

**Issue by JustinGOSSES** [nasa/code-nasa-gov#72]
last pull request broke scrolling on first page, only 12 results show up initially

If you go to code.nasa.gov and scroll down only 12 results show. If you go to another page under code.nasa.gov and then back to the front page, all the results show. 

I suspect this is due to the last update from the most recent pull requests.

**Comment by JustinGOSSES** [comment]
@jMuzsik flagging you on this one as I believe it might have been your pull request that started this behavior, but I haven't investigated it fully yet.

**Comment by jMuzsik** [comment]
@JustinGOSSES I just did a pull request that fixes this. It was because I deleted some invalid css and didn't think about the fact that it was validating a selector right below it which was the reason for the bug.
