### ISSUE TITLE
Too many fonts?

### ISSUE THREAD

**Issue by Saturate** [nasa/code-nasa-gov#9]
Considering the following code:

```
 WebFont.load({
    google: {
        families: ['Inconsolata', 'Source Code Pro', 'Droid Sans Mono', 'Exo 2:400,600,700', 'Special Elite']
    }
});
```

This site uses 5 custom fonts, I would argure that it's a bit over the top, both considering design but also performance wise.

**Comment by addyosmani** [comment]
Indeed! I would argue that there definitely are too many web fonts, but to start we wanted to avoid going through a redesign of Nasa's codesite front-end and just focus on perf improvements. Switching to async Web Fonts has landed in master and should be deployed this week. 

We'll probably explore a way simpler proposal for how this looks (including fewer fonts) once #1 and other low hanging fruit get tackled.
